---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  labels:
    appname: nodejs-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbdmirror
...
